### ISSUE TITLE
Configuring to use GPU from within Livebook?

### ISSUE THREAD

**Issue by dfischer** [livebook-dev/kino_bumblebee#8]
Forgive me if wrong repo.

1) I think it would make sense to have a toggle GPU option or client within Livebook.
2) Is there a way to enable GPU support for m1 Mac?

**Comment by josevalim** [comment]
Unfortunately GPUs are not that plug and play due to cuda/cudnn versions. If you click the help box though, we link you to the next steps.

EXLA does not support GPU on M1 Mac but Torchx does. We will start testing this particular integration soon. You can track it here: https://github.com/elixir-nx/bumblebee/issues/94 :)
